In [5]:
import pandas as pd
from google.colab import files

uploaded = files.upload()

Saving original.csv to original.csv


In [6]:
import pandas as pd  #bir şirketin yaptığı reklam harcamaları sonucunda satışların sonuçları verilmştir bağımlı değişken satışlar, bağımsız diğerleri
df=pd.read_csv("./original.csv")
df=df.iloc[:,1:len(df)] #index problemi olduğu için seçim işlemini yapar
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [0]:
X=df.drop('sales', axis=1) #bağımsız değişkenler
y=df[["sales"]]  #bağımlı değişken (iki köşeli p. ile pandas dataframe şeklinde gelir.)

In [12]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [9]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [0]:
##Statsmodels ile model kurmak

In [0]:
import statsmodels.api as sm
lm=sm.OLS(y, X)

In [15]:
model=lm.fit()
model.summary()  #modelin özetleri

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Sun, 29 Mar 2020   Prob (F-statistic):                   2.43e-171
Time:                        11:18:17   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""



*   Buradaki r kare değeri=bağımsız değişkenlerin bağımlı değişkendeki değişikliği açıklama yüzdesidir. (R-squared ) 
Buradaki değer oldukça yüksek bu da satışlardaki değişimi açıklamak için çok iyi 3 tane değer var.

*   Prob (F-statistic) 0.05 değerinden küçük olduğu için model anlamlıdır.
*   Coef ifadesi bağımsız değişkenlerin kat sayısını verir.

Coef katsayı yorumlama= diğer değişkenler sabit varsayıldığında tv harcamalarında meydana gelebilecek bir birimlik artış bağımlı değişkenimiz sales yani satışlar değişkeninde ortalama 0.053 birim artışa sebep olacaktır.
Radyo harcamalrında bir birimlik artış olduğunda satışlarda ort 0.22 artış olduğu beklenmektedir. 



In [0]:
##scikit learn ile model kurmak

In [0]:
from sklearn.linear_model import LinearRegression
lm=LinearRegression()

In [17]:
model=lm.fit(X,y)  #fit et regrasion modeli kur demek
model.intercept_  #sabit

array([2.93888937])

In [18]:
model.coef_ #bağımsız değişkenlere erişkin katsayı değerleri

array([[ 0.04576465,  0.18853002, -0.00103749]])

**Tahmin**

Sales=2.94+TV*0.04+radio*0.19-newspaper*0.001

In [19]:
#30 br tv, 10 br radio, 40 br gazete tahmini yapılırsa (bazı katsylar negatif yönlü de gelebilir bu bağımlı değişkene olan etkileri için kull.)
2.94+30*0.04+10*0.19-40*0.001

5.999999999999999

In [0]:
yeni_veri=[[30],[10],[40]]

In [22]:
import pandas as pd
yeni_veri=pd.DataFrame(yeni_veri).T

yeni_veri

0   1   2
0  30  10  40

In [23]:
model.predict(yeni_veri) #tahmin edilen değer

array([[6.15562918]])

In [24]:
from sklearn.metrics import mean_squared_error  #hata kareler ortalaması

y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [25]:
model.predict(X)[0:10]  #yşapka değrleri

array([[20.52397441],
       [12.33785482],
       [12.30767078],
       [17.59782951],
       [13.18867186],
       [12.47834763],
       [11.72975995],
       [12.12295317],
       [ 3.72734086],
       [12.55084872]])

In [27]:
MSE=mean_squared_error(y,model.predict(X)) #sol gerçek değerler sağ tahmin edilen değerler
MSE

2.784126314510936

In [28]:
import numpy as np

RMSE=np.sqrt(MSE) #karekökünü alma
RMSE

1.6685701407225697

**Model Tuning(Model Doğrulama)**

Burada bir hiperparametre olmadığından dolayı, model tuning değil de aslında model doğrulama yapılır.
Model doğrulama=

In [29]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [30]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [0]:
##sınama seti
from sklearn.model_selection import train_test_split  #bu fonksiyon ile veri setini ayırma işlemi yapılmış olacak

In [35]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.20, random_state=99)
X_train.head()

TV  radio  newspaper
16    67.8   36.6      114.0
51   100.4    9.6        3.6
97   184.9   21.0       22.0
164  117.2   14.7        5.4
71   109.8   14.3       31.7

In [36]:
X_test.head()

TV  radio  newspaper
135  48.3   47.0        8.5
127  80.2    0.0        9.2
191  75.5   10.8        6.0
66   31.5   24.6        2.2
119  19.4   16.0       22.3

In [37]:
y_train.head()

sales
16    12.5
51    10.7
97    15.5
164   11.9
71    12.4

In [39]:
y_test.head()

sales
135   11.6
127    8.8
191    9.9
66     9.5
119    6.6

In [40]:
lm=LinearRegression()
model=lm.fit(X_train, y_train)

np.sqrt(mean_squared_error(y_train, model.predict(X_train))) #eğitim hatası

1.723682482265075

In [41]:
np.sqrt(mean_squared_error(y_test, model.predict(X_test))) #test hatası

1.4312783138301646

In [42]:
#k-katlı cv
from sklearn.model_selection import cross_val_score
cross_val_score(model, X_train, y_train, cv=10, scoring="neg_mean_squared_error") #train seti kendi içinde 10 parçaya bölündü. 9 parçayla model kurulup dışarıda kalan bir parça tahmin edildi. 10 tanesi için de ayrı ayrı bu şekilde yapıldı.

array([-2.1019073 , -2.48953197, -3.09704214, -2.34694216, -3.68175761,
       -1.8691401 , -3.18173007, -4.1927349 , -2.17128376, -8.03821974])

In [43]:
#cv mse
np.mean(-cross_val_score(model, X_train, y_train, cv=10, scoring="neg_mean_squared_error"))

3.3170289742341255

In [44]:
#cv rmse
np.sqrt(np.mean(-cross_val_score(model, X_train, y_train, cv=10, scoring="neg_mean_squared_error")))

1.8212712522395245

Bunu neden yapıyoruz? Bu işlem bize sadece tek başına test ve trainin vermiş olduğu hatadan daha doğru bir hata ölçüsü verir yani doğrulanmıştır. Modeli Doğrulamak demektir. Farklı varyasyonlara ilişkin hata hesaplaması yapılır bir defa değil 10 kere yapılır ve hepsinin ortalaması alındığında bize valida edilmiş hatayı verir. 